# Generated by Django 5.2.5 on 2025-08-24 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beds_available', models.PositiveIntegerField(default=0)),
                ('icu_beds_available', models.PositiveIntegerField(default=0)),
                ('oxygen_cylinders_available', models.PositiveIntegerField(default=0)),
                ('specialists_available', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
