# Generated by Django 5.2.5 on 2025-08-28 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_condition', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('required_specialists', models.PositiveIntegerField(default=0)),
                ('required_icu', models.BooleanField(default=False)),
                ('required_oxygen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='resourcestatus',
            name='beds_available',
        ),
        migrations.RemoveField(
            model_name='resourcestatus',
            name='icu_beds_available',
        ),
        migrations.RemoveField(
            model_name='resourcestatus',
            name='oxygen_cylinders_available',
        ),
        migrations.RemoveField(
            model_name='resourcestatus',
            name='specialists_available',
        ),
        migrations.RemoveField(
            model_name='resourcestatus',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='resourcestatus',
            name='available_doctors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resourcestatus',
            name='beds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resourcestatus',
            name='icu_beds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resourcestatus',
            name='oxygen_cylinders',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resourcestatus',
            name='hospital',
            field=models.OneToOneField(limit_choices_to={'role': 'hospital_admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='resource_status', to=settings.AUTH_USER_MODEL),
        ),
    ]
