# Generated by Django 5.2.5 on 2025-08-30 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_transferlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergencyrequest',
            old_name='latitude',
            new_name='location_lat',
        ),
        migrations.RenameField(
            model_name='emergencyrequest',
            old_name='longitude',
            new_name='location_long',
        ),
    ]
