# Generated by Django 5.2.5 on 2025-08-21 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('condition_type', models.CharField(choices=[('cardiac', 'Cardiac'), ('accident', 'Accident'), ('respiratory', 'Respiratory'), ('diabetic', 'Diabetic'), ('birth', 'Birth'), ('stroke', 'Stroke'), ('other', 'Other')], max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Assigned'), ('C', 'Completed')], default='P', max_length=1)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
